# Generated by Django 5.1 on 2024-09-13 08:28

import helper.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to=helper.storage.upload_producer_logo_image)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
    ]
