# Generated by Django 5.1 on 2024-09-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='producers', to='category.category'),
        ),
    ]
