# Generated by Django 5.1 on 2024-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('producer', '0002_producer_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='categories',
            field=models.ManyToManyField(related_name='producers', to='category.category'),
        ),
    ]
