# Generated by Django 4.2.16 on 2024-10-04 20:28

from django.db import migrations, models
import helper.storage


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_producer_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='logo',
            field=models.ImageField(upload_to=helper.storage.upload_producer_logo_image),
        ),
    ]
