# Generated by Django 4.2.16 on 2024-09-22 16:39

from django.db import migrations, models
import helper.storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_groups_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=helper.storage.upload_user_image),
        ),
    ]
