# Generated by Django 4.2.16 on 2024-10-04 20:06

from django.db import migrations, models
import helper.storage


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=helper.storage.upload_category_image),
        ),
    ]
