# Generated by Django 4.2.16 on 2024-09-25 17:28

from django.db import migrations, models
import helper.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=helper.storage.upload_product_image),
        ),
    ]
