# Generated by Django 4.2.16 on 2024-10-04 20:06

from django.db import migrations, models
import helper.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=helper.storage.upload_product_image),
        ),
    ]
